config/routes.rb
Rails.application.routes.draw do
  
  root "updates#index"
  
  resources :updates
  
  #API call: HTTP GET json data
  namespace :api do
    namespace :v1 do
      get '/admins/:username', to: "admins#show"
    end
  end
  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  
end

app/models/update.rb
class Update < ActiveRecord::Base
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
   
   def index
   
   end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/api/v1/admins_controller.rb
class Api::V1::AdminsController < ApplicationController
   
   #specify group name to return JSON data
   def show
      @admin = Admin.find_by(username: params[:username])
      @updates = Update.where(admin_id: @admin)
      render json: @updates
   end
   
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
   
   def index
       @updates = Update.all
   end
   
   def show
       @update = Update.find(params[:id])
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head profile="http://www.w3.org/2005/10/profile">
    <!--tags for mobile-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
  <title>News Updates - Android/Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container">
    <a href = "http://zainzulfiqar.com"><p class="navbar-text navcolor">Back to Zain Zulfiqar</p></a>
  </div>
</nav>
  
  <div class = "page container-fluid">
    <!--put the defined views and their pages below-->
    <%= yield %>
  </div>

</body>
</html>

app/views/updates/index.html.erb
<h1 class = "text-center">Latest Updates</h1>
<hr/>
<div class = "table container-fluid">
  <div class="list-group">
  
  <% @updates.each do |update| %>  
  <%= link_to update_path(update), class: "list-group-item" do %>
  <div>
    <h3 class="list-group-item-heading"><%= update.title %></h3>
    <p class="list-group-item-text subtext lead"><%= truncate(update.details, length: 70, separator: ' ') %></p>
  </div>
  <% end %>
  <% end %>
  
  </div>
</div>

<!--Make the link below switch between login or logout based on session id-->
<p class="lead text-center"><%= link_to "Logout", '', class: "customLink" %></p>

app/views/updates/show.html.erb
<div class="task_nav">
  <%= link_to "Back", updates_path, class: "btn btn-default" %>
</div>
<h1 class = "text-center"><%= @update.title %></h1>
<hr/>
<div class = "table container-fluid">
  <p> 
    <%= simple_format(@update.details, class: "lead") %>
  </p>
</div>